### ISSUE TITLE
Credentials for demo

### ISSUE THREAD

**Issue by ujjalacharya** [mrcaidev/HR-management-system#1]
Can you please provide the credentials to check out the demo of the application?

**Comment by mrcaidev** [comment]
Of course!

```
DB_HOST=localhost       # Database Host IP
DB_PORT=5432            # Database port
DB_NAME=human_resource  # Database name
DB_USER=postgres        # Database user
DB_PASSWORD=XXXXXXXX    # Database user password
JWT_SECRET=HRSYSTEM     # Salt for Json Web Token
```

I wrote this project a few months ago, and it's really just for archiving my college coursework. There are other setups like bringing up the datebase (with the .sql files in database/) but I'm not sure now how to set them up... So forgive me if the code cannot run properly or has a bad taste ORZ I'm new to frontend at that time

**Comment by ujjalacharya** [comment]
aah thanks, however I was talking about the link https://hr-management-system.vercel.app/login

**Comment by mrcaidev** [comment]
- 999 for HR manager
- 101 for Section manager
- 200 for Staff

**Comment by ujjalacharya** [comment]
> * 999 for HR manager
> * 101 for Section manager
> * 200 for Staff

and the password?

**Comment by mrcaidev** [comment]
Account and password are the same
